accounts/urls.py
from django.contrib import admin
from django.urls import path

from .views import login_view

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
]

category/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'category'

urlpatterns = [
    path('<int:pk>', views.category_page, name='category'),
]

magazine/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

router = [
    path('category/', include('category.endpoints.categories')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('products/', include('products.urls')),
    path('category/', include('category.urls')),
    path('auth/', include('accounts.urls')),
    path('api/', include(router)),
    path('adpanel/category/', include('adpanel.urls.category')),
    path('adpanel/products/', include('adpanel.urls.products')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main_page, name='index'),
    path('contacts.html', views.contacts_page, name='contacts'),
]

magazine/templates/magazine/master.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block page_title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'packages/bootstrap_3.3.7-dist/css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'styles/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>
</head>
<body>
    <div class="wrapper">
        <div class="navbar navbar-default navbar-static-top">
            <div class="container row">
                <div class="navbar-collapse">
                    <ul data-xs="5" class="nav navbar-nav nav-xs about_company hidden-xs">
                        <li><a href="#">О компании</a></li>
                        <li><a href="#">Доставка и оплата</a></li>
                        <li><a href="#">Гарантия</a></li>
                        <li><a href="{% url 'main:contacts' %}">Контакты</a></li>
                    </ul>
                <div class="visiable-xs hidden-sm hidden-lg hidden-md">
                    <span class="col-xs-8 name_on_xs">BEER4DEER</span>
                    <ul class="nav navbar-nav navbar-right col-sm-4">
                        <li>
                            <div class="col-xs-3">
                                {% if user.is_authenticated  %}
                                    <small>{{ user }}</small>
                                {% else %}
                                    <a href="{% url 'accounts:login' %}">Вход</a> <span>|</span>
                                    <a href="{% url 'accounts:login' %}">Регистрация</a>
                                {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
                    <ul class="nav navbar-nav navbar-right hidden-xs">
                        <li>
                            <div id="lk-link" data-xs="2" data-sm="1">
                                {% if user.is_authenticated  %}
                                        <small class="user-name-span">Привет, {{ user }}!</small>
                                    {% else %}
                                        <a href="{% url 'accounts:login' %}">Вход</a> <span>|</span>
                                        <a href="{% url 'accounts:login' %}">Регистрация</a>
                                    {% endif %}
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="header">
            <div class="container row header_wrap">
                <div class="logo col-sm-5 col-xs-12">
                    <a href="{% url 'main:index' %}"><img src="../media/images/new_logo.png" alt="Логотип"></a>
                </div>
                <div class="header_SM hidden-xs">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-youtube"></i></a>
                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                </div>
                <div class="header_title_wrap">
                </div>
            </div>
        </div>
        <nav class="nav_menu hidden-sm hidden-xs">
            <div class="container">
                <ul id="nav_left" class="navbar navbar-horizontal main_menu">
                    <!--<li class="">-->
                        <!--<a href="{% url 'category:category' pk=2 %}" class="">Аудио/видео</a>-->
                    <!--</li>-->
                    <!--<li class="">-->
                        <!--<a href="{% url 'category:category' pk=3 %}" class="">Мобильные устройства</a>-->
                    <!--</li>-->
                    <!--<li class="">-->
                        <!--<a href="{% url 'category:category' pk=4 %}" class="">Фото</a>-->
                    <!--</li>-->
                </ul>
                <ul id="nav-right" class="navbar navbar-horizontal main_menu">
                    <li class="">
                        <a href="#" class=""><i class="fas fa-shopping-cart"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
        <nav class="navbar navbar-default xs_navbar visible-xs">
            <div class="container-fluid">
                <ul class="nav navbar-nav dropdown_catalog">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Каталог товаров <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Аудио</a></li>
                            <li><a href="#">Фото</a></li>
                            <li><a href="#">Мобильная техника</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class=""><i class="fas fa-shopping-cart"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="content">
            {% block content_block %}
            {% endblock %}
        </div>
        <hr class="before-footer">
        <div class="footer container">
            <footer>&copy; 2018. Все права защищены. Сайт не предназначен для просмотра лицами младше 18 лет!
            </footer>
        </div>
    </div>
<script type="text/javascript" src="{% static 'js/menu.js' %}"></script>
<script>
    axios.get('http://127.0.0.1:8000/api/category/')
        .then(renderData)
</script>
<script src="{% static 'packages/jquery/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'packages/bootstrap_3.3.7-dist/js/bootstrap.min.js' %}"></script>
</body>
</html>