magazine/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

router = [
    path('category/', include('category.endpoints.categories')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('products/', include('products.urls')),
    path('category/', include('category.urls')),
    path('auth/', include('accounts.urls')),
    path('api/', include(router)),
    path('adpanel/category/', include('adpanel.urls.category')),
    path('adpanel/products/', include('adpanel.urls.products')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main_page, name='index'),
    path('contacts.html', views.contacts_page, name='contacts'),
]

products/urls.py
from django.contrib import admin
from django.urls import path

from products.views import ProductModelDetail

app_name = 'products'

urlpatterns = [
    path('<int:pk>', ProductModelDetail.as_view(), name='product'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, get_list_or_404
from django.core.paginator import Paginator

from products.models import Product


def main_page(request):
    template_name = 'magazine/index.html'
    query = get_list_or_404(Product)
    paginator = Paginator(query, 3)
    page = request.GET.get('page')
    items_1 = paginator.get_page(page)
    items_2 = paginator.get_page(2)
    return render(request, template_name, {'result_1': items_1, 'result_2': items_2})


def contacts_page(request):
    return render(request, "magazine/contacts.html", {})

main/templates/magazine/contacts.html
{% extends 'magazine/master.html' %}
{% load staticfiles %}

{% block page_title %}
Контакты
{% endblock%}

{% block content_block %}
        <h2> Контакты </h2>
        <fieldset>
            <legend>Напишите нам</legend>
            <form action="contacts.html" method="post" class="contact-form">
                <input name="login" type="text" placeholder="Введите ваше имя">
                <br>
                <input name="email" type="email" placeholder="Введите ваш email">
                <br>
                <input name="theme" type="text" placeholder="Тема сообщения">
                <br>
                <label for="full_text"> Текст сообщения </label>
                <br>
                <textarea id="full_text" cols="40" rows="3"> </textarea>
                <br>
                <input type="submit" value="Отправить">
                <input type="reset" value="Очистить">
            </form>
        </fieldset>
        <h2> Адрес </h2> <br>
        Телефон: +7-915-999-99-00 <br>
        Адрес: ул. Сокольнический вал д. 52/6 <br>
        email: beer4deer@gmail.com
        <script type="text/javascript" charset="utf-8"
                async
                src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A51923855fee39fc8d80c08bda8de8d85cfcef1f5136141f0aba27fdefa4bd4f0&amp;width=100%&amp;height=374&amp;lang=ru_RU&amp;scroll=true"></script>

{% endblock %}

main/templates/magazine/index.html
{% extends 'magazine/master.html' %}
{% load staticfiles %}

{% block page_title %}
Главная страница
{% endblock%}

{% block content_block %}
<div class="content_header content_new_header">
    Новинки
</div>
<div class="flex-container">
    {% for item in result_1 %}
    <div class="flex-item">
        <a href="{% url 'products:product' pk=item.id %}">
            <img class="product__image" src="../media/{{ item.url }}"></img>
            <h2 class="product__title">
                {{ item.name|title }}
            </h2>
            <span class="product__price">
                                {{ item.price }} Руб.
                            </span>
            <button class="add_trash">
                <i class="fas fa-shopping-cart"></i>
                В корзину
            </button>
        </a>
    </div>
    {% endfor %}
</div>
<div class="content_header">
    Популярные
</div>
<div class="flex-container">
    {% for item in result_2 %}
    <div class="flex-item">
        <a href="{% url 'products:product' pk=item.id %}">
            <img class="product__image" src="../media/{{ item.url }}"></img>
            <h2 class="product__title">
                {{ item.name|title }}
            </h2>
            <span class="product__price">
                                {{ item.price }} Руб.
                            </span>
            <button class="add_trash">
                <i class="fas fa-shopping-cart"></i>
                В корзину
            </button>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}